In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
#import gmaps.datasets
import requests
# Import the API key.
from config import g_key
#!jupyter nbextension enable --py gmaps

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Butaritari,KI,2022-08-29 12:06:20,3.0707,172.7902,82.09,71,67,16.46
1,1,Bluff,NZ,2022-08-29 12:06:21,-46.6000,168.3333,44.80,84,9,6.24
2,2,Chlorakas,CY,2022-08-29 12:06:21,34.8042,32.4083,87.55,74,20,19.57
3,3,Thompson,CA,2022-08-29 12:06:21,55.7435,-97.8558,55.56,100,100,12.66
4,4,Hilo,US,2022-08-29 12:03:55,19.7297,-155.0900,77.29,78,0,6.91

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 75

In [10]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
6,6,Dwarahat,IN,2022-08-29 12:06:22,29.7833,79.4333,70.09,93,93,3.33
26,26,Hasaki,JP,2022-08-29 12:03:40,35.7333,140.8333,70.20,84,100,15.57
27,27,Rikitea,PF,2022-08-29 12:06:29,-23.1203,-134.9692,70.63,82,33,15.52
28,28,Jamestown,US,2022-08-29 12:02:24,42.0970,-79.2353,74.52,66,0,8.05
32,32,Sao Joao Da Barra,BR,2022-08-29 12:06:30,-21.6403,-41.0511,71.69,76,22,23.11
35,35,Shimoda,JP,2022-08-29 12:06:31,34.6667,138.9500,73.36,83,97,15.26
41,41,Albany,US,2022-08-29 12:02:25,42.6001,-73.9662,71.37,90,75,3.33
45,45,Santa Isabel Do Rio Negro,BR,2022-08-29 12:06:34,-0.4139,-65.0192,72.93,97,97,1.99
53,53,Bambanglipuro,ID,2022-08-29 12:07:36,-7.9500,110.2833,74.91,80,52,6.04
56,56,Nouadhibou,MR,2022-08-29 12:07:37,20.9310,-17.0347,74.50,77,16,16.31

In [11]:
preferred_cities_df.count()

City_ID       61
City          61
Country       60
Date          61
Lat           61
Lng           61
Max Temp      61
Humidity      61
Cloudiness    61
Wind Speed    61
dtype: int64

In [12]:
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
6,6,Dwarahat,IN,2022-08-29 12:06:22,29.7833,79.4333,70.09,93,93,3.33
26,26,Hasaki,JP,2022-08-29 12:03:40,35.7333,140.8333,70.20,84,100,15.57
27,27,Rikitea,PF,2022-08-29 12:06:29,-23.1203,-134.9692,70.63,82,33,15.52
28,28,Jamestown,US,2022-08-29 12:02:24,42.0970,-79.2353,74.52,66,0,8.05
32,32,Sao Joao Da Barra,BR,2022-08-29 12:06:30,-21.6403,-41.0511,71.69,76,22,23.11
35,35,Shimoda,JP,2022-08-29 12:06:31,34.6667,138.9500,73.36,83,97,15.26
41,41,Albany,US,2022-08-29 12:02:25,42.6001,-73.9662,71.37,90,75,3.33
45,45,Santa Isabel Do Rio Negro,BR,2022-08-29 12:06:34,-0.4139,-65.0192,72.93,97,97,1.99
53,53,Bambanglipuro,ID,2022-08-29 12:07:36,-7.9500,110.2833,74.91,80,52,6.04
56,56,Nouadhibou,MR,2022-08-29 12:07:37,20.9310,-17.0347,74.50,77,16,16.31
59,59,Innisfail,AU,2022-08-29 12:07:38,-17.5333,146.0333,72.10,94,92,9.13
86,86,Nikolskoye,RU,2022-08-29 12:07:47,59.7035,30.7861,73.29,57,47,9.66
109,109,Yichang,CN,2022-08-29 12:08:53,30.7144,111.2847,73.24,83,100,0.83
112,112,Mount Isa,AU,2022-08-29 12:04:15,-20.7333,139.5000,71.37,73,75,8.05
132,132,Vaini,TO,2022-08-29 12:09:01,-21.2000,-175.2000,71.76,94,40,0.00
141,141,Bethel,US,2022-08-29 12:10:09,41.3712,-73.4140,74.01,85,100,0.00
163,163,Araxa,BR,2022-08-29 12:10:06,-19.5933,-46.9406,72.27,39,25,12.08
166,166,Carauari,BR,2022-08-29 12:10:18,-4.8828,-66.8958,70.70,99,100,0.83
172,172,Ginda,IN,2022-08-29 12:10:20,30.6945,78.4932,70.25,90,65,2.48
187,187,Poum,NC,2022-08-29 12:11:25,-20.2333,164.0167,72.32,72,66,16.96
188,188,Palmer,US,2022-08-29 12:11:26,42.1584,-72.3287,71.62,85,100,4.61
190,190,San Ignacio,BZ,2022-08-29 12:11:26,17.1561,-89.0714,73.11,99,37,1.66
191,191,Avera,US,2022-08-29 12:11:27,33.1940,-82.5271,71.65,88,0,5.77
199,199,Arkansas City,US,2022-08-29 12:11:29,37.0620,-97.0384,73.62,83,0,4.61
205,205,Katsuura,JP,2022-08-29 12:11:31,35.1333,140.3000,74.08,84,97,17.16
215,215,Payakumbuh,ID,2022-08-29 12:11:33,-0.2202,100.6308,71.47,98,98,3.31
220,220,Iraquara,BR,2022-08-29 12:11:35,-12.2486,-41.6194,70.30,65,54,6.98
234,234,Los Llanos De Aridane,ES,2022-08-29 12:12:39,28.6585,-17.9182,71.35,75,40,10.36
239,239,Horsham,GB,2022-08-29 12:12:41,51.0640,-0.3272,73.02,53,0,13.80
242,242,Isangel,VU,2022-08-29 12:12:41,-19.5500,169.2667,72.84,81,92,15.95
246,246,Broome,US,2022-08-29 12:10:38,42.2506,-75.8330,74.01,93,100,6.91
251,251,Padang,ID,2022-08-29 12:12:44,-0.9492,100.3543,71.65,93,99,4.07
256,256,Souillac,MU,2022-08-29 12:12:46,-20.5167,57.5167,73.96,69,56,9.13
275,275,Namibe,AO,2022-08-29 12:12:51,-15.1961,12.1522,70.77,69,13,10.87
309,309,Renqiu,CN,2022-08-29 12:14:01,38.6989,116.0936,70.11,76,99,5.39
310,310,Richards Bay,ZA,2022-08-29 12:14:02,-28.7830,32.0377,71.28,69,84,15.77
324,324,Seoul,KR,2022-08-29 12:11:09,37.5683,126.9778,71.04,64,100,4.59
328,328,Boleslawiec,PL,2022-08-29 12:15:08,51.2642,15.5697,72.39,46,1,9.60
341,341,Halifax,CA,2022-08-29 12:10:54,44.6453,-63.5724,70.21,88,70,8.01
342,342,Lalibela,ET,2022-08-29 12:15:12,12.0333,39.0333,70.79,51,98,2.51
375,375,Oneida,US,2022-08-29 12:16:23,43.2001,-75.4663,74.95,84,0,5.75
377,377,Dobson,US,2022-08-29 12:16:23,36.3957,-80.7226,74.53,96,0,0.00
398,398,Panaba,MX,2022-08-29 12:16:30,21.2833,-88.2667,74.71,96,12,5.17
405,405,Camacha,PT,2022-08-29 12:16:32,33.0833,-16.3333,71.02,68,20,5.75
406,406,Puerto Escondido,MX,2022-08-29 12:16:32,15.8500,-97.0667,72.43,78,75,8.05
409,409,Shingu,JP,2022-08-29 12:16:33,33.7333,135.9833,74.07,94,100,7.58
419,419,Chatham,GB,2022-08-29 12:15:42,51.3789,0.5279,72.34,59,50,8.99
429,429,Shelburne,CA,2022-08-29 12:15:50,44.0787,-80.2041,73.85,84,100,13.69
443,443,Tomatlan,MX,2022-08-29 12:17:42,19.9333,-105.2500,73.62,96,100,3.40
455,455,Marawi,PH,2022-08-29 12:17:45,7.9986,124.2928,70.12,93,99,1.34
465,465,Jiuquan,CN,2022-08-29 12:18:48,39.7432,98.5174,74.71,19,91,8.16
467,467,Boffa,GN,2022-08-29 12:18:49,10.1667,-14.0333,74.50,93,100,17.25
471,471,Cobija,BO,2022-08-29 12:18:50,-11.0267,-68.7692,73.58,64,75,13.80
474,474,Morgantown,US,2022-08-29 12:18:51,39.6295,-79.9559,74.71,90,0,0.00
482,482,Kindu,CD,2022-08-29 12:18:53,-2.9500,25.9500,71.80,93,100,0.60
513,513,Topeka,US,2022-08-29 12:16:43,39.0483,-95.6780,73.58,92,0,5.75
532,532,Zhicheng,CN,2022-08-29 12:20:10,30.2956,111.5047,71.28,74,100,2.98
541,541,Bowen,AU,2022-08-29 12:20:13,-20.0167,148.2333,70.99,86,94,18.32
545,545,Northam,GB,2022-08-29 12:20:14,51.0333,-4.2167,72.25,73,13,15.75
559,559,Mingguang,CN,2022-08-29 12:20:19,32.7802,117.9638,74.07,87,100,11.34

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                         City Country  Max Temp      Lat       Lng Hotel Name
6                    Dwarahat      IN     70.09  29.7833   79.4333
26                     Hasaki      JP     70.20  35.7333  140.8333
27                    Rikitea      PF     70.63 -23.1203 -134.9692
28                  Jamestown      US     74.52  42.0970  -79.2353
32          Sao Joao Da Barra      BR     71.69 -21.6403  -41.0511
35                    Shimoda      JP     73.36  34.6667  138.9500
41                     Albany      US     71.37  42.6001  -73.9662
45  Santa Isabel Do Rio Negro      BR     72.93  -0.4139  -65.0192
53              Bambanglipuro      ID     74.91  -7.9500  110.2833
56                 Nouadhibou      MR     74.50  20.9310  -17.0347

In [14]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'AeJbb3fYuOAEpr0pArCrEvElOyso1WhyHE5yT0uAxj5gy_XhkKBMOucSq2w4m1jO5suyDFtIXZyazOaLD58DIHJSWd-5DreJjHdSx9mq3tb3bD2wX9Xp1XbUlxGbKzHHLNKTc0GNUZ_ZoUlCyutdKYf-qiIRbfo5MbutPSagxBxajjirsR9rnU28c-DdJ1UaNEhDgktG6T3bF0dhXQ8tETZcPAGDG6YhiVRJRGCbZsmXjrNIZHucQPLTROa58lhf09YrHrcfn3FEU9AI0_RZSc9aG9ch2vmqtiHCwyI7B03Jb0jFraAoozKx9laN6Tr11de5ePyEbuhNs7gh-0PmpmUGqyFglszVLhJNrx7Fc6bWOkt9QE1GjW0DI8ZeeUQQeMsPNfpBfveWlOgsvmJKrloXwEP3cx0VRySK3nurNfajlDCcwZYZUzdDf5-T',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'AeJbb3eu_svdqh2wi_Q80eV00a0WrrikqijeNjUJTAT5TLgbQXE0NjVyTgqKOJSE23AmUqNV8Ok3CqOICZnMCiC10QThqznRuMpek30A6fxa1D3I46yq2O2axmYAIdm7bMFdvQgIaCm6Ms72DfoIcNKWun0SYRoqSG1e40YPnhm4s9Jim9q0',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.3,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'gym',
    'bar',
    'lodging',
    'spa',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 341,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Britannique Hotel - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'AeJbb3etBOOpK3gyITgORfN2YdPVxOad5Y-6OcZo5brM75rdkgl4hLocLf9xNiDhpbPW7WgRoiw3nX99GsaaqogBR2w0SOCy2W-1WqzqPJ8eDd7MAGNKm61YevZCgHeYOFmg7eIOB-pYorxWyABNHJYe5ARskRQJ-wCPBEzIMtkPZ6f0dQ3Y',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.7,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 732,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606342, 'lng': 2.3468978},
    'viewport': {'northeast': {'lat': 48.8617746302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590766697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Apart&#39;hotel Les Halles Paris</a>'],
     'photo_reference': 'AeJbb3cj6RfQtXi8oaDU5Zgl2686jSyNKz1ljG_h2B88dQcaRkMQd8GfyGroGH01A8PUuDTkLQnfIxMFjAjJT0ABHM1-iMV4wlgHYXrebt0u3zhkIQd4kh1xOxaYmjKXcZI5mmxE7OCGtzM-Ol0WG6ttq_UXPcaNclPHttX9NCGI2VldVbsf',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['city_hall',
    'lodging',
    'local_government_office',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 934,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'AeJbb3fGDWX3sRQjNHiGXB8XlydJVjnSlbwUlHUanr4YIC5g94t7uYQ0JNaM6JuG7JWYIbW-UAFUxhw2_H26dHiyDG5zvv1irVN3fPhkjY6uJ61wGoXc1r91p0u-JmmSckvzJdHHluQCn3jzDeELCmjBKotsyJiH9Dxcaju3K0Ob-WvAH3AS',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2627,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'AeJbb3ef7bahUGzRRTylTpIelv0Q_0mZmSa7oE-_UXXMlgWU13k0eZE3iDwmhIadieEpITM1horNLsqZbD7zSfuhdTqCX_x_k_q6iBl6w3i_l8UUJI1gMCjudrhn8w9hB7Yr7TTBQRtMiOloWgaqI-kA1M4O3sZPXzOx40MskTj5PdnNM4BM',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 311,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'AeJbb3frs2Ioq_veoZdr4rcwH1Lkpi2lHvpy4MPQHSo1AoI2acKAYdYrRBzRFbrc-p7BIf3Wbco-PRCkI4deNI3SLb51_OpyokmkmEnwesQb2rpjbH4KgVdqT4EI9jqm1C46KNrvEZOXtS6irmJtbIrsV-ZiRzqlMBjsCY88dQOxHUI8DMim',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['city_hall',
    'lodging',
    'local_government_office',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 755,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8524547, 'lng': 2.3472064},
    'viewport': {'northeast': {'lat': 48.8538838802915,
      'lng': 2.348601530291502},
     'southwest': {'lat': 48.8511859197085, 'lng': 2.345903569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Esmeralda',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1960,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106443224837840180239">Fraz A. Khan</a>'],
     'photo_reference': 'AeJbb3euzPY3qo1WegVLKCk3heJFZbdMyb3NXCNnoAF9G9tN1uvpNu6IRmDA_B2HgxmXw6fB6fIhwFdUuICsOIyh-6n0VsBGQwrAPu79Ktmv89D8xjUlnQf2dq_ZOWwSLM3kxDyUwpx4JLU8Jdsof7iuhTFG7MLH36gfqcXhcKbafc7hRaK9',
     'width': 4032}],
   'place_id': 'ChIJO_g_H-Fx5kcRmaabUHA3dT4',
   'plus_code': {'compound_code': 'V82W+XV Paris, France',
    'global_code': '8FW4V82W+XV'},
   'rating': 4.1,
   'reference': 'ChIJO_g_H-Fx5kcRmaabUHA3dT4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 173,
   'vicinity': '4 Rue Saint-Julien le Pauvre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8530901, 'lng': 2.3447174},
    'viewport': {'northeast': {'lat': 48.8544535802915,
      'lng': 2.345997680291501},
     'southwest': {'lat': 48.85175561970851, 'lng': 2.343299719708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Albe Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1152,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117571951379278191466">Albe Hotel Saint Michel</a>'],
     'photo_reference': 'AeJbb3djieXeWKd3j-D3_gosi-oftO46PsthkKR00tEEwBbvfqdLtOMIFjZOvdm7xgvxHFpBeI00fQf81pIjGZd40TZiiu35Mv3A0cHPg-1GwgLMveq69mlkQ3m8BZJdFls008d9Iq65HgRfr_GmNP2-FDmzJXR9svwm9CCWMSpSGI0xEi39',
     'width': 1600}],
   'place_id': 'ChIJ8R5-hOBx5kcRsCOdfj8GLeY',
   'plus_code': {'compound_code': 'V83V+6V Paris, France',
    'global_code': '8FW4V83V+6V'},
   'rating': 4.4,
   'reference': 'ChIJ8R5-hOBx5kcRsCOdfj8GLeY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 378,
   'vicinity': '1 Rue de la Harpe, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8532403, 'lng': 2.3457375},
    'viewport': {'northeast': {'lat': 48.85462748029149,
      'lng': 2.347175730291502},
     'southwest': {'lat': 48.8519295197085, 'lng': 2.344477769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Les Rives de Notre-Dame Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116242575283063930652">Michael Scholz</a>'],
     'photo_reference': 'AeJbb3dpwmaKJOVJ_r_WIfxAJaNKWSUGLdXe-A05Hr9W-k4JPtcemZsfErNBCARo5nzS1peyx6Oq3zA7qzdDmzVbrkG8hkhkteV-Dkz3pCX7RbtyIyouOu2F9LyR3qZuBIE_AW1yx8No3t4-IFcwwRXEnPQ3kDh2Yko_7OVZJWWJ2DK-yics',
     'width': 6048}],
   'place_id': 'ChIJl7vs8-Bx5kcRfIQzq_4_XmU',
   'plus_code': {'compound_code': 'V83W+77 Paris, France',
    'global_code': '8FW4V83W+77'},
   'rating': 4.5,
   'reference': 'ChIJl7vs8-Bx5kcRfIQzq_4_XmU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 102,
   'vicinity': '15 Quai Saint-Michel, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.85184049999999, 'lng': 2.3448082},
    'viewport': {'northeast': {'lat': 48.8531470802915,
      'lng': 2.346121880291502},
     'southwest': {'lat': 48.8504491197085, 'lng': 2.343423919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel 4 étoiles Parc Saint-Séverin Paris 5ème - Esprit de France',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2362,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107542132357877294567">Hôtel 4 étoiles Parc Saint Séverin Paris 5ème - Esprit de France</a>'],
     'photo_reference': 'AeJbb3cXTrCtP1fcbVPVBCV3oqSwZ0D4h1nbOhS8JAJakpwv9Fizprl6lPd9Z44KkDcDW0AQfx8wQon7JzgcBrG4ir2hwdDUbMckCo-4TDm4mEvFvqEVrH5U1goyg_tZlYnU6B6aYpLWOknuca9J_J371dbD80OK8vjizsOHCQYr-e_5K59n',
     'width': 3776}],
   'place_id': 'ChIJ9--kuuBx5kcRojwQ1yEK2cY',
   'plus_code': {'compound_code': 'V82V+PW Paris, France',
    'global_code': '8FW4V82V+PW'},
   'rating': 4.6,
   'reference': 'ChIJ9--kuuBx5kcRojwQ1yEK2cY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 188,
   'vicinity': '22 Rue de la Parcheminerie, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8518743, 'lng': 2.3463436},
    'viewport': {'northeast': {'lat': 48.8532481802915,
      'lng': 2.347596830291502},
     'southwest': {'lat': 48.8505502197085, 'lng': 2.344898869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Henri IV Rive Gauche',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117561863517287206024">Muzafar Husain</a>'],
     'photo_reference': 'AeJbb3dMVG6n5cbUCzi29t476Dq-gW9Lt59oX_tVAy8H2v-DrWj1gMAaykeECePwImR6iGJlckL0UgE280S-1HsRSf9pq61AaTHKP1BLSfpIExh35YR4Rz9w-9_vySeqb9nla8TAW_xb6H_fObN2M9mPBnXsh9S_Nc-PJPwVNEddLzJ6KWsu',
     'width': 3024}],
   'place_id': 'ChIJ2a4f2-Bx5kcR40Wl3uv_53Y',
   'plus_code': {'compound_code': 'V82W+PG Paris, France',
    'global_code': '8FW4V82W+PG'},
   'rating': 4.5,
   'reference': 'ChIJ2a4f2-Bx5kcR40Wl3uv_53Y',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 171,
   'vicinity': 'Rue Saint-Jacques, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8600866, 'lng': 2.3533543},
    'viewport': {'northeast': {'lat': 48.86148808029149,
      'lng': 2.354740780291502},
     'southwest': {'lat': 48.85879011970849, 'lng': 2.352042819708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Beaubourg',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3744,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115421447635584539926">Hôtel Beaubourg</a>'],
     'photo_reference': 'AeJbb3eb4pviNiXcrSFCjDHMUmHQQkM4-yQ9vvXQjTiiRsGA-_ykFvo7JaCLkCaDGPR8-n2ROp4dI8YMmTxGd5Tn0biDZP7GhP8bXtLSHyXDSOadBN3g8w0B8kGcO4xUXiSUdRKc1XhYWeq5FSWweOzAF-NAP1EpBUwzTWwo8ba2sNvzZWNx',
     'width': 5616}],
   'place_id': 'ChIJCdHKjhxu5kcR0YtyGr7Vftc',
   'plus_code': {'compound_code': 'V963+28 Paris, France',
    'global_code': '8FW4V963+28'},
   'rating': 4.3,
   'reference': 'ChIJCdHKjhxu5kcR0YtyGr7Vftc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 163,
   'vicinity': '11 Rue Simon le Franc, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.859876, 'lng': 2.347049},
    'viewport': {'northeast': {'lat': 48.8610872802915,
      'lng': 2.348425880291502},
     'southwest': {'lat': 48.8583893197085, 'lng': 2.345727919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': "Hôtel Des Ducs D'Anjou",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115209143941459061727">Hotel Des Ducs D&#39;Anjou</a>'],
     'photo_reference': 'AeJbb3cpUZEedsN00km7j_3IbCdYfpHEj4-FLfCu2o7YqNeMIuxhh2S2XgRCHh1KLqTio1lIU4I2bmEczZ0ZkYDi-RE0nhAN65qYBxhKRPzVpZFk1eZwUNkgB-jStSAmG63VCfSKisV_MIgobUzRvt576AcRvrTM6cXYXnaxNwPykm6TVWBj',
     'width': 1352}],
   'place_id': 'ChIJ9ekWGR9u5kcRsS8j5TnWeSE',
   'plus_code': {'compound_code': 'V85W+XR Paris, France',
    'global_code': '8FW4V85W+XR'},
   'rating': 3.9,
   'reference': 'ChIJ9ekWGR9u5kcRsS8j5TnWeSE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 335,
   'vicinity': '1 Rue Sainte-Opportune, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8515237, 'lng': 2.3486679},
    'viewport': {'northeast': {'lat': 48.8529256302915,
      'lng': 2.349962130291502},
     'southwest': {'lat': 48.8502276697085, 'lng': 2.347264169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Maison Colbert Member of Meliá Collection',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3656,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102194778927204133336">Hotel Maison Colbert Member of Meliá Collection</a>'],
     'photo_reference': 'AeJbb3eI5DoXCf-3NJ5XYjZPIJSFLorizHSuNtHQGJvBpxhvh3Dp4ZBNdl4k2NtJxuuu3fJb3ZCjV2zhTbl4e0u6bU-uywWLxEJgZU6YAyGFOcOADnCwxoycF2LezGR9u75_W0X1XmtgayI2k-wzQfXzUzIoHXFWgr2SD5c28o5vY0kxDzcx',
     'width': 3543}],
   'place_id': 'ChIJI3vbSOFx5kcR84E4IeL2LqI',
   'plus_code': {'compound_code': 'V82X+JF Paris, France',
    'global_code': '8FW4V82X+JF'},
   'rating': 4.7,
   'reference': 'ChIJI3vbSOFx5kcR84E4IeL2LqI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 24,
   'vicinity': "7 Rue de l'Hôtel Colbert, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8499446, 'lng': 2.346247699999999},
    'viewport': {'northeast': {'lat': 48.8513264802915,
      'lng': 2.347622530291501},
     'southwest': {'lat': 48.8486285197085, 'lng': 2.344924569708497}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Home Latin',
   'photos': [{'height': 4080,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113966656287531023757">Ioan Mihael</a>'],

In [15]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [16]:
hotel_df.head()

,City,Country,Max Temp,Lat,Lng,Hotel Name
6,Dwarahat,IN,70.09,29.7833,79.4333,"Mayank Resort,Dwarahat"
26,Hasaki,JP,70.20,35.7333,140.8333,Inubosaki Kanko Hotel
27,Rikitea,PF,70.63,-23.1203,-134.9692,People ThankYou
28,Jamestown,US,74.52,42.0970,-79.2353,Hampton Inn & Suites Jamestown
32,Sao Joao Da Barra,BR,71.69,-21.6403,-41.0511,Pousada Porto De Canoas

In [17]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [24]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [25]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))